FROM jakutenshi/ubuntu-dev:latest

# Step 1
RUN git config --global user.name "Your_name"
RUN git config --global user.email yourname@yourmail.com
RUN apt-get update
RUN apt-get install -y ruby-dev bundler clang
RUN git clone https://github.com/orocos-toolchain/build.git
WORKDIR build/
RUN git checkout toolchain-2.8-16.04
WORKDIR /root/
COPY installation_guide.md manual_from_step_2.md
