FROM jakutenshi/ubuntu-dev:latest

# Step 1
RUN git config --global user.name "Your_name"                  \
    && git config --global user.email yourname@yourmail.com    \
#    && git clone https://github.com/orocos-toolchain/build.git \
    && apt-get update                                          \
    && apt-get install -y ruby-dev bundler clang
ADD build.tar.gz /root/
WORKDIR /root/build/
RUN git checkout toolchain-2.8-16.04
WORKDIR /root/
COPY installation_guide.md manual_from_step_2.md
