\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdftitle={Пример обработки данных},
            pdfauthor={Ефремов Михаил},
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}
  \title{Пример обработки данных}
  \pretitle{\vspace{\droptitle}\centering\huge}
  \posttitle{\par}
  \author{Ефремов Михаил}
  \preauthor{\centering\large\emph}
  \postauthor{\par}
  \date{}
  \predate{}\postdate{}


\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\hypertarget{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varsubs_count-where-size1024-buffer1}{%
\subsection{Benchmark name is
``PublisherFixture/ROS\_BM\_Publish\_method'' by var=subs\_count where
size=1024
buffer=1}\label{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varsubs_count-where-size1024-buffer1}}

\begin{verbatim}
##   factor real_time cpu_time bytes_per_second manual_bandwidth
## 1      1  5427.760 5232.933        195766631         88444996
## 2      2  6576.162 6050.106        338793970        184995399
##   manual_latency
## 1      193478517
## 2      197417815
\end{verbatim}

\includegraphics{result_files/figure-latex/unnamed-chunk-1-1.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-1-2.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-1-3.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-1-4.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-1-5.pdf}

\hypertarget{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varsubs_count-where-size1024-buffer10}{%
\subsection{Benchmark name is
``PublisherFixture/ROS\_BM\_Publish\_method'' by var=subs\_count where
size=1024
buffer=10}\label{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varsubs_count-where-size1024-buffer10}}

\begin{verbatim}
##   factor real_time cpu_time bytes_per_second manual_bandwidth
## 1      1  5619.260 5404.915        189558762         95480711
## 2      2  6721.198 6153.360        333592051        178253801
##   manual_latency
## 1      193920098
## 2      210970582
\end{verbatim}

\includegraphics{result_files/figure-latex/unnamed-chunk-2-1.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-2-2.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-2-3.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-2-4.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-2-5.pdf}

\hypertarget{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varsubs_count-where-size2048-buffer1}{%
\subsection{Benchmark name is
``PublisherFixture/ROS\_BM\_Publish\_method'' by var=subs\_count where
size=2048
buffer=1}\label{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varsubs_count-where-size2048-buffer1}}

\begin{verbatim}
##   factor real_time cpu_time bytes_per_second manual_bandwidth
## 1      1  5834.122 5631.738        363761557        135470881
## 2      2  6903.844 6445.975        637147572        223029226
##   manual_latency
## 1      153198937
## 2      160782538
\end{verbatim}

\includegraphics{result_files/figure-latex/unnamed-chunk-3-1.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-3-2.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-3-3.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-3-4.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-3-5.pdf}

\hypertarget{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varsubs_count-where-size2048-buffer10}{%
\subsection{Benchmark name is
``PublisherFixture/ROS\_BM\_Publish\_method'' by var=subs\_count where
size=2048
buffer=10}\label{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varsubs_count-where-size2048-buffer10}}

\begin{verbatim}
##   factor real_time cpu_time bytes_per_second manual_bandwidth
## 1      1  5891.138 5679.259        360679662        153702492
## 2      2  6763.762 6270.046        655066216        192957573
##   manual_latency
## 1      153139816
## 2      145779904
\end{verbatim}

\includegraphics{result_files/figure-latex/unnamed-chunk-4-1.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-4-2.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-4-3.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-4-4.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-4-5.pdf}

\hypertarget{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varsubs_count-where-size4096-buffer1}{%
\subsection{Benchmark name is
``PublisherFixture/ROS\_BM\_Publish\_method'' by var=subs\_count where
size=4096
buffer=1}\label{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varsubs_count-where-size4096-buffer1}}

\begin{verbatim}
##   factor real_time cpu_time bytes_per_second manual_bandwidth
## 1      1  5727.588 5610.791        730188420        213533427
## 2      2  6933.439 6491.932       1264312856        382479966
##   manual_latency
## 1      131764704
## 2      139443250
\end{verbatim}

\includegraphics{result_files/figure-latex/unnamed-chunk-5-1.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-5-2.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-5-3.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-5-4.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-5-5.pdf}

\hypertarget{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varsubs_count-where-size4096-buffer10}{%
\subsection{Benchmark name is
``PublisherFixture/ROS\_BM\_Publish\_method'' by var=subs\_count where
size=4096
buffer=10}\label{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varsubs_count-where-size4096-buffer10}}

\begin{verbatim}
##   factor real_time cpu_time bytes_per_second manual_bandwidth
## 1      1  5868.970 5729.758        715051066        199229907
## 2      2  6765.752 6396.280       1284242978        373380194
##   manual_latency
## 1      131373129
## 2      135796168
\end{verbatim}

\includegraphics{result_files/figure-latex/unnamed-chunk-6-1.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-6-2.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-6-3.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-6-4.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-6-5.pdf}

\hypertarget{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varsize-where-subs_count1-buffer1}{%
\subsection{Benchmark name is
``PublisherFixture/ROS\_BM\_Publish\_method'' by var=size where
subs\_count=1
buffer=1}\label{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varsize-where-subs_count1-buffer1}}

\begin{verbatim}
##   factor real_time cpu_time bytes_per_second manual_bandwidth
## 1   1024  5427.760 5232.933        195766631         88444996
## 2   2048  5834.122 5631.738        363761557        135470881
## 3   4096  5727.588 5610.791        730188420        213533427
##   manual_latency
## 1      193478517
## 2      153198937
## 3      131764704
\end{verbatim}

\includegraphics{result_files/figure-latex/unnamed-chunk-7-1.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-7-2.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-7-3.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-7-4.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-7-5.pdf}

\hypertarget{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varsize-where-subs_count1-buffer10}{%
\subsection{Benchmark name is
``PublisherFixture/ROS\_BM\_Publish\_method'' by var=size where
subs\_count=1
buffer=10}\label{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varsize-where-subs_count1-buffer10}}

\begin{verbatim}
##   factor real_time cpu_time bytes_per_second manual_bandwidth
## 1   1024  5619.260 5404.915        189558762         95480711
## 2   2048  5891.138 5679.259        360679662        153702492
## 3   4096  5868.970 5729.758        715051066        199229907
##   manual_latency
## 1      193920098
## 2      153139816
## 3      131373129
\end{verbatim}

\includegraphics{result_files/figure-latex/unnamed-chunk-8-1.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-8-2.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-8-3.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-8-4.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-8-5.pdf}

\hypertarget{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varsize-where-subs_count2-buffer1}{%
\subsection{Benchmark name is
``PublisherFixture/ROS\_BM\_Publish\_method'' by var=size where
subs\_count=2
buffer=1}\label{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varsize-where-subs_count2-buffer1}}

\begin{verbatim}
##   factor real_time cpu_time bytes_per_second manual_bandwidth
## 1   1024  6576.162 6050.106        338793970        184995399
## 2   2048  6903.844 6445.975        637147572        223029226
## 3   4096  6933.439 6491.932       1264312856        382479966
##   manual_latency
## 1      197417815
## 2      160782538
## 3      139443250
\end{verbatim}

\includegraphics{result_files/figure-latex/unnamed-chunk-9-1.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-9-2.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-9-3.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-9-4.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-9-5.pdf}

\hypertarget{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varsize-where-subs_count2-buffer10}{%
\subsection{Benchmark name is
``PublisherFixture/ROS\_BM\_Publish\_method'' by var=size where
subs\_count=2
buffer=10}\label{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varsize-where-subs_count2-buffer10}}

\begin{verbatim}
##   factor real_time cpu_time bytes_per_second manual_bandwidth
## 1   1024  6721.198 6153.360        333592051        178253801
## 2   2048  6763.762 6270.046        655066216        192957573
## 3   4096  6765.752 6396.280       1284242978        373380194
##   manual_latency
## 1      210970582
## 2      145779904
## 3      135796168
\end{verbatim}

\includegraphics{result_files/figure-latex/unnamed-chunk-10-1.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-10-2.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-10-3.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-10-4.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-10-5.pdf}

\hypertarget{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varbuffer-where-subs_count1-size1024}{%
\subsection{Benchmark name is
``PublisherFixture/ROS\_BM\_Publish\_method'' by var=buffer where
subs\_count=1
size=1024}\label{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varbuffer-where-subs_count1-size1024}}

\begin{verbatim}
##   factor real_time cpu_time bytes_per_second manual_bandwidth
## 1      1   5427.76 5232.933        195766631         88444996
## 2     10   5619.26 5404.915        189558762         95480711
##   manual_latency
## 1      193478517
## 2      193920098
\end{verbatim}

\includegraphics{result_files/figure-latex/unnamed-chunk-11-1.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-11-2.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-11-3.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-11-4.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-11-5.pdf}

\hypertarget{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varbuffer-where-subs_count1-size2048}{%
\subsection{Benchmark name is
``PublisherFixture/ROS\_BM\_Publish\_method'' by var=buffer where
subs\_count=1
size=2048}\label{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varbuffer-where-subs_count1-size2048}}

\begin{verbatim}
##   factor real_time cpu_time bytes_per_second manual_bandwidth
## 1      1  5834.122 5631.738        363761557        135470881
## 2     10  5891.138 5679.259        360679662        153702492
##   manual_latency
## 1      153198937
## 2      153139816
\end{verbatim}

\includegraphics{result_files/figure-latex/unnamed-chunk-12-1.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-12-2.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-12-3.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-12-4.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-12-5.pdf}

\hypertarget{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varbuffer-where-subs_count1-size4096}{%
\subsection{Benchmark name is
``PublisherFixture/ROS\_BM\_Publish\_method'' by var=buffer where
subs\_count=1
size=4096}\label{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varbuffer-where-subs_count1-size4096}}

\begin{verbatim}
##   factor real_time cpu_time bytes_per_second manual_bandwidth
## 1      1  5727.588 5610.791        730188420        213533427
## 2     10  5868.970 5729.758        715051066        199229907
##   manual_latency
## 1      131764704
## 2      131373129
\end{verbatim}

\includegraphics{result_files/figure-latex/unnamed-chunk-13-1.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-13-2.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-13-3.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-13-4.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-13-5.pdf}

\hypertarget{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varbuffer-where-subs_count2-size1024}{%
\subsection{Benchmark name is
``PublisherFixture/ROS\_BM\_Publish\_method'' by var=buffer where
subs\_count=2
size=1024}\label{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varbuffer-where-subs_count2-size1024}}

\begin{verbatim}
##   factor real_time cpu_time bytes_per_second manual_bandwidth
## 1      1  6576.162 6050.106        338793970        184995399
## 2     10  6721.198 6153.360        333592051        178253801
##   manual_latency
## 1      197417815
## 2      210970582
\end{verbatim}

\includegraphics{result_files/figure-latex/unnamed-chunk-14-1.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-14-2.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-14-3.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-14-4.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-14-5.pdf}

\hypertarget{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varbuffer-where-subs_count2-size2048}{%
\subsection{Benchmark name is
``PublisherFixture/ROS\_BM\_Publish\_method'' by var=buffer where
subs\_count=2
size=2048}\label{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varbuffer-where-subs_count2-size2048}}

\begin{verbatim}
##   factor real_time cpu_time bytes_per_second manual_bandwidth
## 1      1  6903.844 6445.975        637147572        223029226
## 2     10  6763.762 6270.046        655066216        192957573
##   manual_latency
## 1      160782538
## 2      145779904
\end{verbatim}

\includegraphics{result_files/figure-latex/unnamed-chunk-15-1.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-15-2.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-15-3.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-15-4.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-15-5.pdf}

\hypertarget{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varbuffer-where-subs_count2-size4096}{%
\subsection{Benchmark name is
``PublisherFixture/ROS\_BM\_Publish\_method'' by var=buffer where
subs\_count=2
size=4096}\label{benchmark-name-is-publisherfixtureros_bm_publish_method-by-varbuffer-where-subs_count2-size4096}}

\begin{verbatim}
##   factor real_time cpu_time bytes_per_second manual_bandwidth
## 1      1  6933.439 6491.932       1264312856        382479966
## 2     10  6765.752 6396.280       1284242978        373380194
##   manual_latency
## 1      139443250
## 2      135796168
\end{verbatim}

\includegraphics{result_files/figure-latex/unnamed-chunk-16-1.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-16-2.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-16-3.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-16-4.pdf}
\includegraphics{result_files/figure-latex/unnamed-chunk-16-5.pdf}


\end{document}
